//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predbiljezba
    {
        public int idPredbiljezbe { get; set; }
        public System.DateTime Datum { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Adresa { get; set; }
        public string Email { get; set; }
        public string BrojTelefona { get; set; }
        public int idSeminar { get; set; }
        public Nullable<bool> StatusDaNe { get; set; }
    
        public virtual Seminari Seminari { get; set; }
    }
}
