//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Se
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seminari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seminari()
        {
            this.Predbiljezba = new HashSet<Predbiljezba>();
        }
    
        public int id { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public System.DateTime Datum { get; set; }
        public bool PopunjenDaNe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predbiljezba> Predbiljezba { get; set; }
    }
}
